# Generated by Django 5.2.3 on 2025-07-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
