# Generated by Django 5.2.3 on 2025-07-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_cliente_correo_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
    ]
